# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: 3Kontact.3Kontact
PackageVersion: 5.10.5.9143
PackageLocale: da-DK
Publisher: 3Kontact
PublisherUrl: https://www.3.dk/
Author: 3Kontact
PackageName: 3Kontact
License: Proprietary
Copyright: © 2024 - 3 (Hi3G Denmark ApS)
ShortDescription: 3Kontakt makes it easy for you to handle all your calls - even when you are busy or in a meeting. Our user-friendly app allows you and your company to manage communication efficiently.
ManifestType: defaultLocale
ManifestVersion: 1.10.0
